// <auto-generated />
using System;
using Gateway.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gateway.Infrastructure.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260206025938_AddAggregationTables")]
    partial class AddAggregationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "timescaledb");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gateway.Infrastructure.Data.SensorAggregation10MinEntity", b =>
                {
                    b.Property<DateTime>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket");

                    b.Property<int>("FactoryId")
                        .HasColumnType("integer")
                        .HasColumnName("factory_id");

                    b.Property<string>("Tag")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tag");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("equipment_type");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("equipment_name");

                    b.Property<string>("SourceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_id");

                    b.Property<decimal>("AvgValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_value");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTime>("LastTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_timestamp");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("max_value");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric")
                        .HasColumnName("min_value");

                    b.HasKey("Bucket", "FactoryId", "Tag", "EquipmentType", "EquipmentName", "SourceId");

                    b.HasIndex("Bucket")
                        .IsDescending()
                        .HasDatabaseName("IX_sensor_agg_10min_bucket");

                    b.HasIndex("LastTimestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_sensor_agg_10min_last_timestamp");

                    b.HasIndex("FactoryId", "Tag", "Bucket")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_sensor_agg_10min_factory_tag_bucket");

                    b.ToTable("sensor_agg_10min", (string)null);
                });

            modelBuilder.Entity("Gateway.Infrastructure.Data.SensorAggregation1HourEntity", b =>
                {
                    b.Property<DateTime>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket");

                    b.Property<int>("FactoryId")
                        .HasColumnType("integer")
                        .HasColumnName("factory_id");

                    b.Property<string>("Tag")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tag");

                    b.Property<string>("EquipmentType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("equipment_type");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("equipment_name");

                    b.Property<string>("SourceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_id");

                    b.Property<decimal>("AvgValue")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_value");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("max_value");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric")
                        .HasColumnName("min_value");

                    b.HasKey("Bucket", "FactoryId", "Tag", "EquipmentType", "EquipmentName", "SourceId");

                    b.HasIndex("Bucket")
                        .IsDescending()
                        .HasDatabaseName("IX_sensor_agg_1hour_bucket");

                    b.HasIndex("FactoryId", "Tag", "Bucket")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_sensor_agg_1hour_factory_tag_bucket");

                    b.ToTable("sensor_agg_1hour", (string)null);
                });

            modelBuilder.Entity("Gateway.Infrastructure.Data.TelemetryEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("equipment_name");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("equipment_type");

                    b.Property<int>("FactoryId")
                        .HasColumnType("integer")
                        .HasColumnName("factory_id");

                    b.Property<int>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<string>("RouteKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("route_key");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tag");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trace_id");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("EventId", "Timestamp");

                    b.HasIndex("EquipmentName")
                        .HasDatabaseName("IX_telemetry_events_equipment_name");

                    b.HasIndex("EquipmentType")
                        .HasDatabaseName("IX_telemetry_events_equipment_type");

                    b.HasIndex("FactoryId")
                        .HasDatabaseName("IX_telemetry_events_factory_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("IX_telemetry_events_source_id");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_telemetry_events_tag");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_telemetry_events_timestamp");

                    b.HasIndex("FactoryId", "Timestamp")
                        .HasDatabaseName("IX_telemetry_events_factory_timestamp");

                    b.HasIndex("SourceId", "Timestamp")
                        .HasDatabaseName("IX_telemetry_events_source_timestamp");

                    b.HasIndex("FactoryId", "EquipmentType", "Timestamp")
                        .HasDatabaseName("IX_telemetry_events_factory_equipment_timestamp");

                    b.ToTable("telemetry_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
